/**
 * CRUDE8 STUDIO: CODE GENERATION ENGINE
 * Produces deployable artifacts from a StudioModuleProject: database schema,
 * governed API routes, React list/form components, validation schema,
 * tests and documentation. Every artifact is derived from the registry —
 * DEFINE ONCE. GENERATE EVERYWHERE.
 */

import { StudioModuleProject } from './studio-types';

function prismaType(fieldType: string): string {
  switch (fieldType) {
    case 'NUMBER': return 'Float';
    case 'BOOLEAN': return 'Boolean';
    case 'DATE': return 'DateTime';
    case 'MULTISELECT': return 'Json';
    default: return 'String';
  }
}

function pascal(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

export class StudioCodegenEngine {
  static generateDatabaseSchema(project: StudioModuleProject): string {
    const lines = project.fields.map(fl => {
      const attrs: string[] = [];
      if (fl.unique) attrs.push('@unique');
      if (!fl.required) attrs.push('?');
      const def = fl.defaultValue !== undefined
        ? ` @default(${typeof fl.defaultValue === 'string' ? `"${fl.defaultValue}"` : fl.defaultValue})`
        : '';
      return `  ${fl.name} ${prismaType(fl.type)}${fl.required && !fl.unique ? '' : '?'}${def}`;
    });
    const relations = project.relations.map(r =>
      `  ${r.relationName} ${pascal(r.targetEntity)}? @relation(fields: ["${r.foreignKey}"], references: ["id"])`
    );
    return `// Generated by CRUDE8 Studio — ${project.name} v${project.version}
model ${pascal(project.entityName)} {
  id        String   @id @default(cuid())
  version   Int      @default(1)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  deletedAt DateTime?
${[...lines, ...relations].join('\n')}

  @@index([${project.lifecycleField}])
  @@map("${project.entityName.toLowerCase()}s")
}`;
  }

  static generateApiRoute(project: StudioModuleProject): string {
    return `// Generated by CRUDE8 Studio — governed API for ${project.entityName}
import { NextRequest, NextResponse } from 'next/server';
import { CRUDE8Engine } from '@/lib/crude8/crud-engine';
import { UniversalActionType } from '@/lib/crude8/types';

// POST /api/crude8/${project.entityName}/[action]
export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const action = (body.action || 'CREATE') as UniversalActionType;
  const user = { userId: body.userId, role: body.role, tenantId: body.tenantId };
  try {
    const result = await CRUDE8Engine.execute('${pascal(project.entityName)}' as any, action, user, {
      id: body.id,
      payload: body.payload,
      filters: body.filters,
      expectedVersion: body.expectedVersion
    });
    return NextResponse.json(result);
  } catch (err: any) {
    const status = err.message?.includes('Permission Denied') ? 403 : err.message?.includes('Not Found') ? 404 : 400;
    return NextResponse.json({ success: false, error: err.message }, { status });
  }
}`;
  }

  static generateListComponent(project: StudioModuleProject): string {
    const columns = project.ui.listView.columns;
    const headers = columns.map(c => `<th key="${c}" className="px-4 py-2 text-left text-xs font-bold text-slate-400 uppercase">${c}</th>`).join('\n            ');
    const cells = columns.map(c => `<td key="${c}" className="px-4 py-2 text-sm text-slate-200">{record.${c} != null ? String(record.${c}) : '—'}</td>`).join('\n            ');
    return `// Generated by CRUDE8 Studio — ${project.entityName} List View (${project.ui.listView.type})
'use client';
import React, { useEffect, useState } from 'react';

export function ${pascal(project.entityName)}List() {
  const [records, setRecords] = useState<any[]>([]);

  useEffect(() => {
    fetch('/api/crude8/studio/runtime/${project.entityName.toLowerCase()}')
      .then(res => res.json())
      .then(json => setRecords(json.data || []));
  }, []);

  return (
    <div className="p-6 bg-slate-900/60 border border-slate-800 rounded-2xl">
      <h2 className="text-lg font-black text-white mb-4">${project.entityName}s</h2>
      <table className="w-full">
        <thead>
          <tr>
            ${headers}
          </tr>
        </thead>
        <tbody>
          {records.map(record => (
            <tr key={record.id} className="border-t border-slate-800">
            ${cells}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}`;
  }

  static generateFormComponent(project: StudioModuleProject): string {
    const sectionJsx = project.ui.formView.sections.map(section => `
      <section className="p-4 bg-slate-950 border border-slate-800 rounded-xl">
        <h3 className="text-sm font-bold text-white mb-3">${section.title}</h3>
        <div className="grid grid-cols-${section.columns} gap-3">
${section.fields.map(pf => {
  const field = project.fields.find(fl => fl.name === pf.field);
  if (!field) return '';
  const common = `key="${field.name}" value={form.${field.name} ?? ''} onChange={e => setForm({ ...form, ${field.name}: e.target.value })}`;
  let input: string;
  switch (pf.component) {
    case 'TEXTAREA': case 'RICHTEXT': input = `<textarea ${common} rows={3} className="..." />`; break;
    case 'BOOLEAN': input = `<input type="checkbox" ${common.replace(/e\.target\.value/g, 'e.target.checked')} />`; break;
    case 'DATE': input = `<input type="date" ${common} className="..." />`; break;
    case 'NUMBER': input = `<input type="number" ${common} className="..." />`; break;
    case 'SELECT': case 'MULTISELECT': input = `<select ${common} className="...">${(field.options || []).map(o => `<option key="${o}" value="${o}">${o}</option>`).join('')}</select>`; break;
    default: input = `<input type="text" ${common} className="..." />`;
  }
  return `          <label className="text-xs text-slate-400">${field.label}${field.required ? ' *' : ''}\n            ${input}\n          </label>`;
}).filter(Boolean).join('\n')}
        </div>
      </section>`).join('\n');

    return `// Generated by CRUDE8 Studio — ${project.entityName} Governed Form
'use client';
import React, { useState } from 'react';

export function ${pascal(project.entityName)}Form({ onCreated }: { onCreated?: () => void }) {
  const [form, setForm] = useState<Record<string, any>>({});
  const [error, setError] = useState<string | null>(null);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    const res = await fetch('/api/crude8/studio/runtime/${project.entityName.toLowerCase()}', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ payload: form })
    });
    const json = await res.json();
    if (!json.success) setError(json.error || 'Creation failed');
    else onCreated?.();
  };

  return (
    <form onSubmit={submit} className="space-y-4">
${sectionJsx}
      {error && <div className="text-xs text-rose-400">{error}</div>}
      <button type="submit" className="px-4 py-2 rounded-xl bg-sky-600 text-white text-xs font-bold">
        Create ${project.entityName}
      </button>
    </form>
  );
}`;
  }

  static generateValidation(project: StudioModuleProject): string {
    const rules = project.fields.map(fl => {
      const parts: string[] = [];
      if (fl.required) parts.push('required');
      if (fl.type === 'EMAIL') parts.push('email format');
      if (fl.type === 'NUMBER') parts.push('numeric');
      if (fl.unique) parts.push('globally unique');
      if (fl.options?.length) parts.push(`one of [${fl.options.join(', ')}]`);
      return `  ${fl.name}: ${parts.join('; ') || 'any'}`;
    });
    return `// Generated by CRUDE8 Studio — validation contract for ${project.entityName}
// Enforced server-side by the CRUDE8 validation gate before every mutation.
export const ${pascal(project.entityName)}ValidationRules = {
${rules.join('\n')}
} as const;`;
  }

  static generateTests(project: StudioModuleProject): string {
    const requiredFields = project.fields.filter(fl => fl.required).map(fl => fl.name);
    return `// Generated by CRUDE8 Studio — sandbox test suite for ${project.entityName}
describe('${project.entityName} governed CRUD', () => {
  it('creates a record through the governed pipeline', async () => {
    const res = await sandboxExec('${project.entityName}', 'CREATE', {
      ${requiredFields.map(rf => `${rf}: '<value>'`).join(',\n      ')}
    });
    expect(res.success).toBe(true);
    expect(res.version).toBe(1);
    expect(res.events).toContain('${project.entityName.toUpperCase()}_CREATED');
  });

  it('rejects missing required fields', async () => {
    const res = await sandboxExec('${project.entityName}', 'CREATE', {});
    expect(res.success).toBe(false);
    expect(res.error).toContain('missing required field');
  });

  it('denies destructive actions to non-admin roles', async () => {
    const res = await simulatePermission('AGENT', '${project.entityName}', 'DELETE');
    expect(res.allowed).toBe(false);
  });

  it('runs workflow: ${project.workflows[0]?.name || 'N/A'}', async () => {
    const res = await runWorkflow('${project.workflows[0]?.workflowId || '-'}');
    expect(res.success).toBe(true);
    expect(res.trace.length).toBeGreaterThan(0);
  });
});`;
  }

  static generateDocumentation(project: StudioModuleProject): string {
    return `# ${project.name}

> Generated by CRUDE8 Studio v${project.version} · Mode: ${project.mode} · Module: ${project.module}
> Status: ${project.status} · Origin: ${project.origin}

${project.description}

## Entity: ${project.entityName}
| Field | Type | Required | Unique | Notes |
|-------|------|----------|--------|-------|
${project.fields.map(fl => `| ${fl.name} | ${fl.type} | ${fl.required ? 'yes' : 'no'} | ${fl.unique ? 'yes' : 'no'} | ${fl.options?.length ? fl.options.join('/') : ''} |`).join('\n')}

## Lifecycle
- State field: \`${project.lifecycleField}\`
- Transitions: ${Object.entries(project.lifecycleTransitions).map(([a, s]) => `${a} -> ${s}`).join(', ')}

## Views
- List: ${project.ui.listView.type} (columns: ${project.ui.listView.columns.join(', ')})
- Form sections: ${project.ui.formView.sections.map(s => s.title).join(', ')}
- Detail: ${project.ui.detailView.layout} (${project.ui.detailView.widgets.join(', ')})
- Dashboard stats: ${project.ui.dashboard.stats.map(s => `${s.agg}(${s.field})`).join(', ')}

## Governed Actions
${project.actions.map(a => `- **${a.name}** (${a.trigger}): ${a.steps.map(s => s.type).join(' -> ')}`).join('\n')}

## Workflows
${project.workflows.length ? project.workflows.map(w => `- **${w.name}** on \`${w.triggerEvent}\`: ${w.nodes.map(n => n.name).join(' -> ')}`).join('\n') : '- None defined'}

## Permissions (explicit rules)
${project.permissions.rules.map(r => `- ${r.role}: ${r.action} = ${r.allowed ? 'ALLOWED' : 'DENIED'} (${r.scope})`).join('\n')}

## Events
${project.events.map(e => `- \`${e.eventName}\` (${e.trigger}) -> subscribers: ${e.subscribers.join(', ') || 'none'}`).join('\n')}

## Automations
${project.automations.length ? project.automations.map(a => `- **${a.name}** on \`${a.trigger}\`: ${a.actions.join(' -> ')}`).join('\n') : '- None defined'}

## AI Actions
${project.aiActions.length ? project.aiActions.map(a => `- ${a}`).join('\n') : '- None'}

## Reports
${project.reports.map(r => `- ${r}`).join('\n')}

## Sync Targets
${project.syncTargets.join(', ') || 'None'}
`;
  }

  static generateAll(project: StudioModuleProject): Record<string, string> {
    return {
      databaseSchema: this.generateDatabaseSchema(project),
      apiRoute: this.generateApiRoute(project),
      listComponent: this.generateListComponent(project),
      formComponent: this.generateFormComponent(project),
      validation: this.generateValidation(project),
      tests: this.generateTests(project),
      documentation: this.generateDocumentation(project)
    };
  }
}
