/**
 * CRUDE8 STUDIO: DATA MOCK ENGINE
 * Generates realistic, relationship-aware sample records from a Studio
 * entity schema — including edge cases (missing optionals, expired dates,
 * boundary values) — for safe sandbox simulation.
 */

import { StudioField, StudioModuleProject } from './studio-types';

const FIRST_NAMES = ['Aarav', 'Priya', 'Rohan', 'Ananya', 'Vikram', 'Meera', 'Arjun', 'Kavya', 'Rajesh', 'Divya', 'Sandeep', 'Nisha', 'Karan', 'Pooja', 'Aditya', 'Sneha'];
const LAST_NAMES = ['Sharma', 'Patel', 'Iyer', 'Reddy', 'Khan', 'Nair', 'Gupta', 'Mehta', 'Pillai', 'Joshi', 'Verma', 'Rao'];
const CITIES = ['Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Jaipur', 'Kochi', 'Goa'];
const COUNTRIES = ['India', 'UAE', 'Singapore', 'Thailand', 'Japan', 'USA', 'UK', 'Australia'];
const COMPANIES = ['Skyline Travels', 'Wanderlust Tours', 'Everest Expeditions', 'Coastal Holidays', 'Royal Journeys', 'Nomad Ventures', 'Zenith Tourism', 'Bluewave Holidays'];
const HOTELS = ['Taj Lakeview', 'Marriott Grand', 'Cliffside Resort', 'Palm Lagoon', 'Heritage Haveli', 'Alpine Lodge'];
const CATEGORIES = ['AIRLINE', 'HOTEL_CHAIN', 'DMC', 'TRANSPORT', 'GUIDE'];
const EMAIL_DOMAINS = ['example.com', 'mail.example.in', 'corp.example.org'];

function pick<T>(arr: T[], seedIdx: number): T {
  return arr[Math.abs(seedIdx) % arr.length];
}

function hashOf(seed: string): number {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  return h;
}

function valueForField(field: StudioField, idx: number, entityLower: string): any {
  const seed = hashOf(`${entityLower}:${field.name}:${idx}`);
  const name = field.name.toLowerCase();

  switch (field.type) {
    case 'EMAIL': {
      const first = pick(FIRST_NAMES, seed).toLowerCase();
      const last = pick(LAST_NAMES, seed >> 3).toLowerCase();
      return `${first}.${last}${idx}@${pick(EMAIL_DOMAINS, seed >> 5)}`;
    }
    case 'PHONE':
      return `+91 ${90000 + (seed % 9999)} ${10000 + (seed >> 4) % 99999}`;
    case 'NUMBER': {
      if (/price|amount|budget|salary|cost|total|revenue/.test(name)) return 2500 + (seed % 40) * 1250;
      if (/rating|score/.test(name)) return Math.round(((seed % 30) / 10 + 3) * 10) / 10;
      if (/days|duration|nights/.test(name)) return 3 + (seed % 12);
      if (/count|qty|quantity|rooms|pax|stock/.test(name)) return seed % 120;
      if (/percent/.test(name)) return seed % 101;
      return seed % 500;
    }
    case 'BOOLEAN':
      return seed % 10 < 7;
    case 'DATE': {
      const now = Date.now();
      const day = 24 * 60 * 60 * 1000;
      if (/expiry|expir|deadline|due|return/.test(name)) return new Date(now + ((seed % 200) - 20) * day).toISOString().slice(0, 10);
      if (/birth|dob/.test(name)) return new Date(now - (20 + (seed % 25)) * 365 * day).toISOString().slice(0, 10);
      if (/join|created|issue|start/.test(name)) return new Date(now - (seed % 400) * day).toISOString().slice(0, 10);
      return new Date(now + (seed % 120) * day).toISOString().slice(0, 10);
    }
    case 'SELECT':
      return field.options?.length ? pick(field.options, seed) : 'ACTIVE';
    case 'MULTISELECT': {
      const opts = field.options || ['STANDARD'];
      return [pick(opts, seed), pick(opts, seed >> 2)].filter((v, i, a) => a.indexOf(v) === i);
    }
    case 'RELATION':
      return undefined; // resolved against generated parents by the caller
    case 'FILE':
    case 'IMAGE':
      return `https://blob.travelplanet.in/sandbox/${entityLower}/${field.name}-${idx}.pdf`;
    case 'TEXTAREA':
    case 'RICHTEXT':
      return `${field.label} sample content for record #${idx} — auto-generated by the CRUDE8 Data Mock Engine for sandbox simulation.`;
    case 'AI':
      return null; // AI fields stay empty in mocks; populated by AI actions
    case 'VOICE':
    case 'SIGNATURE':
    case 'MAP':
      return field.type === 'MAP' ? { lat: 19.07 + (seed % 100) / 500, lng: 72.87 + (seed % 100) / 500 } : null;
    case 'TEXT':
    default: {
      if (/^id$/.test(name) || /number$/.test(name) || /code$/.test(name)) return `${entityLower.slice(0, 3)}-${1000 + idx}`;
      if (/slug/.test(name)) return `${entityLower}-${pick(CITIES, seed).toLowerCase()}-${idx}`;
      if (/name|title/.test(name)) {
        if (/hotel|property|resort/.test(entityLower)) return pick(HOTELS, seed);
        if (/supplier|company|vendor|agency/.test(name) || /supplier/.test(entityLower)) return pick(COMPANIES, seed);
        return `${pick(FIRST_NAMES, seed)} ${pick(LAST_NAMES, seed >> 4)}`;
      }
      if (/city/.test(name)) return pick(CITIES, seed);
      if (/country|destination|region/.test(name)) return pick(COUNTRIES, seed);
      if (/status/.test(name)) return field.options?.length ? pick(field.options, seed) : 'ACTIVE';
      if (/url|link/.test(name)) return `https://cdn.travelplanet.in/sandbox/${entityLower}/${idx}`;
      if (/descri|note|comment/.test(name)) return `Auto-generated ${field.label.toLowerCase()} for sandbox record #${idx}.`;
      return `${field.label} ${idx}`;
    }
  }
}

export interface MockGenerationOptions {
  count?: number;
  includeEdgeCases?: boolean;
  relatedIds?: Record<string, string[]>;
}

export class StudioDataMockEngine {
  /**
   * Generates mock records for a studio project's entity.
   * relatedIds maps relation fields -> available parent record ids.
   */
  static generateMockRecords(project: StudioModuleProject, options: MockGenerationOptions = {}): Record<string, any>[] {
    const count = options.count ?? 25;
    const edgeCases = options.includeEdgeCases ?? true;
    const entityLower = project.entityName.toLowerCase();
    const lifecycleField = project.lifecycleField;
    const lifecycleValues = Object.values(project.lifecycleTransitions);
    const statusOptions = project.fields.find(f => f.name === lifecycleField)?.options;

    const records: Record<string, any>[] = [];
    for (let i = 0; i < count; i++) {
      const record: Record<string, any> = {
        id: `${entityLower}-mock-${1000 + i}`,
        version: 1
      };

      for (const field of project.fields) {
        if (field.name === 'id' || field.name === 'version') continue;

        // Edge cases: every 7th record drops an optional field, every 11th zeroes a number
        const isEdgeSkip = edgeCases && i % 7 === 6 && !field.required;
        if (isEdgeSkip) continue;

        if (field.type === 'RELATION') {
          const parents = options.relatedIds?.[field.name];
          record[field.name] = parents?.length ? parents[i % parents.length] : undefined;
          continue;
        }

        record[field.name] = valueForField(field, i, entityLower);
      }

      // Keep the lifecycle field coherent
      if (statusOptions?.length) {
        record[lifecycleField] = pick(statusOptions, i);
      } else if (lifecycleValues.length && record[lifecycleField] === undefined) {
        record[lifecycleField] = lifecycleValues[0];
      }

      records.push(record);
    }

    return records;
  }

  /**
   * Generates related parents first, then children with FK wiring.
   * `relatedSpec` maps FK field name -> { project, count }.
   */
  static generateWithRelations(
    project: StudioModuleProject,
    relatedSpec: Record<string, { project: StudioModuleProject; count: number }> | undefined,
    count: number
  ): { entity: Record<string, any>[]; related: Record<string, Record<string, any>[]> } {
    const related: Record<string, Record<string, any>[]> = {};
    const relatedIds: Record<string, string[]> = {};

    if (relatedSpec) {
      for (const [fkField, spec] of Object.entries(relatedSpec)) {
        related[spec.project.entityName] = this.generateMockRecords(spec.project, { count: spec.count, includeEdgeCases: false });
        relatedIds[fkField] = related[spec.project.entityName].map(r => r.id);
      }
    }

    const entity = this.generateMockRecords(project, { count, includeEdgeCases: true, relatedIds });
    return { entity, related };
  }
}
